# Generated by Django 6.0.5 on 2026-05-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_upgrade_moderator_to_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
