# Generated by Django 6.0.5 on 2026-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userfollow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following'], name='userfollow_following_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='userfollow_no_self_follow'),
        ),
    ]
