# Generated by Django 6.0.5 on 2026-06-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar_alter_user_profile_public'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userfollow',
            name='userfollow_following_idx',
        ),
    ]
