services:
  db:
    image: postgres
    container_name: books-db
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-key
    ports:
      - "5432:5432"