INSERT INTO books (title, author, year) VALUES
('Wiedzmin: Ostatnie zyczenie', 'Andrzej Sapkowski', 1993),
('Wiedzmin: Miecz przeznaczenia', 'Andrzej Sapkowski', 1992),
('Krew elfow', 'Andrzej Sapkowski', 1994),
('Chrzest ognia', 'Andrzej Sapkowski', 1996),
('Pan Lodowego Ogrodu', 'Jaroslaw Grzedowicz', 2005),
('Limes Inferior', 'Janusz A. Zajdel', 1982),
('Paradyzja', 'Janusz A. Zajdel', 1984),
('Solaris', 'Stanislaw Lem', 1961),
('Cyberiada', 'Stanislaw Lem', 1965),
('Dzienniki gwiazdowe', 'Stanislaw Lem', 1957),
('1984', 'George Orwell', 1949),
('Folwark zwierzecy', 'George Orwell', 1945),
('Nowy wspanialy swiat', 'Aldous Huxley', 1932),
('Diuna', 'Frank Herbert', 1965),
('Fundacja', 'Isaac Asimov', 1951),
('Mistrz i Malgorzata', 'Michail Bulhakow', 1967),
('Imie rozy', 'Umberto Eco', 1980),
('Zbrodnia i kara', 'Fiodor Dostojewski', 1866),
('Rok 1984. Reportaz', 'Mariusz Szczygiel', 2004),
('Maly Ksiaze', 'Antoine de Saint-Exupery', 1943);
