// One wiki Page: frontmatter header, Markdown body, sources/verification footer
import type { ReactNode } from 'react'
import Markdown from 'react-markdown'
import type { Page } from '@/api/types'
import { parsePage } from '@/wiki'

export function PageView({ page, children }: { page: Page; children?: ReactNode }) {
  const { frontmatter: fm, body } = parsePage(page.content)
  const verifiers = (fm.verified ?? []).map((v) => v.by)
  const hasFooter = Boolean(fm.sources?.length || fm.generated || verifiers.length)

  return (
    <>
      <header>
        <p className="font-mono text-xs text-muted-foreground">{page.path}</p>
        <h1 className="mt-1 font-heading text-4xl">{page.title}</h1>
        <p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground">
          <span>{page.type}</span>
          {fm.author && <span>· {fm.author}</span>}
          {fm.status && (
            <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-semibold text-foreground">
              {fm.status}
            </span>
          )}
        </p>
        {fm.description && <p className="mt-3 text-lg text-muted-foreground">{fm.description}</p>}
      </header>

      <div className="page-body mt-6">
        <Markdown>{body}</Markdown>
      </div>

      {children}

      {hasFooter && (
        <footer
          role="contentinfo"
          className="mt-10 flex flex-wrap gap-x-4 gap-y-1.5 border-t pt-4 text-[13px] text-muted-foreground"
        >
          {fm.sources?.length ? (
            <span>
              Sources:{' '}
              {fm.sources.map((s, i) => (
                <span key={s.id}>
                  {i > 0 && ', '}
                  {s.resource ? (
                    <a
                      href={s.resource}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                    >
                      {s.title ?? s.id}
                    </a>
                  ) : (
                    (s.title ?? s.id)
                  )}
                </span>
              ))}
            </span>
          ) : null}
          {fm.generated && <span>Generated by {fm.generated.by}</span>}
          {verifiers.length > 0 && <span>verified by {verifiers.join(', ')}</span>}
        </footer>
      )}
    </>
  )
}
