// One wiki Page: frontmatter header, Markdown body, sources/verification footer
import { Link } from '@tanstack/react-router'
import type { ComponentProps, ReactNode } from 'react'
import Markdown, { type ExtraProps } from 'react-markdown'
import { usePages } from '@/api/hooks'
import type { Page } from '@/api/types'
import { pageSplat, parsePage } from '@/wiki'

export function PageView({ page, children }: { page: Page; children?: ReactNode }) {
  const { frontmatter: fm, body } = parsePage(page.content)
  const verifiers = (fm.verified ?? []).map((v) => v.by)
  const hasFooter = Boolean(fm.sources?.length || fm.generated || verifiers.length)

  return (
    <>
      <header>
        <p className="font-mono text-xs text-muted-foreground">{page.path}</p>
        <h1 className="mt-1 font-heading text-4xl">{page.title}</h1>
        <p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground">
          <span>{page.type}</span>
          {fm.author && <span>· {fm.author}</span>}
          {fm.status && (
            <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-semibold text-foreground">
              {fm.status}
            </span>
          )}
        </p>
        {fm.description && <p className="mt-3 text-lg text-muted-foreground">{fm.description}</p>}
      </header>

      <div className="page-body mt-6">
        <Markdown components={{ a: WikiLink }}>{body}</Markdown>
      </div>

      {children}

      {hasFooter && (
        <footer
          role="contentinfo"
          className="mt-10 flex flex-wrap gap-x-4 gap-y-1.5 border-t pt-4 text-[13px] text-muted-foreground"
        >
          {fm.sources?.length ? (
            <span>
              Sources:{' '}
              {fm.sources.map((s, i) => (
                <span key={s.id}>
                  {i > 0 && ', '}
                  {s.resource ? (
                    <a
                      href={s.resource}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                    >
                      {s.title ?? s.id}
                    </a>
                  ) : (
                    (s.title ?? s.id)
                  )}
                </span>
              ))}
            </span>
          ) : null}
          {fm.generated && <span>Generated by {fm.generated.by}</span>}
          {verifiers.length > 0 && <span>verified by {verifiers.join(', ')}</span>}
        </footer>
      )}
    </>
  )
}

const badge = 'inline-flex items-center gap-1.5 rounded-full px-3 py-0.5 text-sm font-semibold'

// Odnośnik: character/place → badge, other wiki Path → link, missing Path → text (OKF tolerates broken links)
function WikiLink({ href = '', children }: ComponentProps<'a'> & ExtraProps) {
  const { data: pages = [] } = usePages()

  if (!href.startsWith('/')) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer" className="text-primary underline">
        {children}
      </a>
    )
  }
  // ponytail: linear scan per link, fine for one user's wiki; build a Set in a hook if pages grow large
  if (!pages.some((p) => p.path === href)) return <span>{children}</span>

  const params = { _splat: pageSplat(href) }
  if (href.startsWith('/characters/')) {
    return (
      <Link to="/$" params={params} className={`${badge} bg-character text-character-foreground`}>
        <PersonIcon />
        {children}
      </Link>
    )
  }
  if (href.startsWith('/places/')) {
    return (
      <Link to="/$" params={params} className={`${badge} bg-place text-place-foreground`}>
        <PinIcon />
        {children}
      </Link>
    )
  }
  return (
    <Link to="/$" params={params} className="text-primary underline">
      {children}
    </Link>
  )
}

const iconProps = {
  width: 13,
  height: 13,
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  strokeWidth: 2,
  'aria-hidden': true,
} as const

const PersonIcon = () => (
  <svg {...iconProps}>
    <circle cx="12" cy="8" r="4" />
    <path d="M4 21c1.5-4 4.5-6 8-6s6.5 2 8 6" />
  </svg>
)

const PinIcon = () => (
  <svg {...iconProps}>
    <path d="M12 21s-7-6.2-7-11a7 7 0 0 1 14 0c0 4.8-7 11-7 11z" />
    <circle cx="12" cy="10" r="2.5" />
  </svg>
)
