# Generated by Django 6.0.5 on 2026-05-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent_of', 'Parent Of'), ('sibling_of', 'Sibling Of'), ('spouse_of', 'Spouse Of'), ('ancestor_of', 'Ancestor Of'), ('friend_of', 'Friend Of'), ('enemy_of', 'Enemy Of'), ('rival_of', 'Rival Of'), ('mentor_of', 'Mentor Of'), ('lover_of', 'Lover Of'), ('admires', 'Admires'), ('ruler_of', 'Ruler Of'), ('commands', 'Commands'), ('serves', 'Serves'), ('member_of_faction', 'Member Of Faction'), ('fights_against', 'Fights Against'), ('protects', 'Protects'), ('betrays', 'Betrays'), ('saves', 'Saves'), ('hunts', 'Hunts'), ('knows_secret_of', 'Knows Secret Of'), ('manipulates', 'Manipulates'), ('deceives', 'Deceives'), ('creator_of', 'Creator Of'), ('clone_of', 'Clone Of')], max_length=30)),
            ],
        ),
    ]
