# Generated by Django 6.0.5 on 2026-05-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcharacter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookorganization',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookplace',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='books.book'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_relationships', to='books.book'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='from_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='analysis.bookcharacter'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='to_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='analysis.bookcharacter'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcharacter',
            unique_together={('name', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='bookorganization',
            unique_together={('name', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='bookplace',
            unique_together={('name', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='characterrelationship',
            unique_together={('from_character', 'to_character', 'book')},
        ),
    ]
