# Generated by Django 6.0.5 on 2026-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('books', '0002_alter_bookauthor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcharacter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bookorganization',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bookplace',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='characterrelationship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookcharacter',
            constraint=models.UniqueConstraint(fields=('name', 'book'), name='unique_character_per_book'),
        ),
        migrations.AddConstraint(
            model_name='bookorganization',
            constraint=models.UniqueConstraint(fields=('name', 'book'), name='unique_org_per_book'),
        ),
        migrations.AddConstraint(
            model_name='bookplace',
            constraint=models.UniqueConstraint(fields=('name', 'book'), name='unique_place_per_book'),
        ),
        migrations.AddConstraint(
            model_name='characterrelationship',
            constraint=models.UniqueConstraint(fields=('from_character', 'to_character', 'book'), name='unique_character_relation_per_book'),
        ),
    ]
