# Generated by Django 6.0.5 on 2026-05-22 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookauthor_unique_together_and_more'),
        ('shelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelfentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='shelfentry',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_shelf'),
        ),
    ]
