# Generated by Django 6.0.5 on 2026-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelf_shelfmembership_shelf_unique_owner_shelf_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
