# Generated by Django 6.0.5 on 2026-05-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_ai_extraction_status'),
        ('shelf', '0002_alter_shelfentry_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShelfMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_memberships', to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shelf.shelf')),
            ],
            options={
                'ordering': ('position', '-added_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_shelf_slug'),
        ),
        migrations.AddIndex(
            model_name='shelfmembership',
            index=models.Index(fields=['shelf', 'position'], name='shelfmembership_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='shelfmembership',
            constraint=models.UniqueConstraint(fields=('shelf', 'book'), name='unique_shelf_book_membership'),
        ),
    ]
