# Generated by Django 6.0.5 on 2026-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_shelfentry_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
