# Generated by Django 6.0.5 on 2026-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_ai_extraction_failure_reason_and_more'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterrelation',
            name='label',
        ),
        migrations.AddField(
            model_name='characterrelation',
            name='relation_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('relative', 'Relative'), ('lover', 'Lover'), ('ex_partner', 'Ex-partner'), ('friend', 'Friend'), ('ally', 'Ally'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('master', 'Master'), ('servant', 'Servant'), ('leader', 'Leader'), ('follower', 'Follower'), ('enemy', 'Enemy'), ('rival', 'Rival'), ('colleague', 'Colleague'), ('acquaintance', 'Acquaintance'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='characterrelation',
            constraint=models.UniqueConstraint(fields=('from_character', 'to_character', 'relation_type'), name='unique_relation_type_per_pair'),
        ),
    ]
