# Generated by Django 6.0.5 on 2026-06-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_characterrelation_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterrelation',
            options={'ordering': ('id',)},
        ),
    ]
