import type { Character } from '$lib/types';

export const fixtureCharacters: Character[] = [
	{
		id: 1,
		name: 'Paul Atreides',
		also_known_as: ["Muad'Dib", 'Usul', 'Lisan al Gaib'],
		role: 'protagonist',
		short_bio: 'The son of Duke Leto and Lady Jessica, trained in the Bene Gesserit Way.',
		long_bio: null,
		tags: ['duke', 'Kwisatz Haderach', 'POV'],
		archetype: 'reluctant chosen one',
		first_appearance_chapter: 1,
		source: 'ai',
		confidence: 0.95,
		book_ids: [1]
	},
	{
		id: 2,
		name: 'Lady Jessica',
		also_known_as: [],
		role: 'supporting',
		short_bio: "Paul's mother, a Bene Gesserit who defied her order.",
		long_bio: null,
		tags: ['Bene Gesserit', 'concubine'],
		archetype: 'protective mother',
		first_appearance_chapter: 1,
		source: 'ai',
		confidence: 0.95,
		book_ids: [1]
	},
	{
		id: 3,
		name: 'Duke Leto Atreides',
		also_known_as: [],
		role: 'supporting',
		short_bio: "Paul's father, a noble and just ruler.",
		long_bio: null,
		tags: ['duke', 'leader'],
		archetype: 'noble ruler',
		first_appearance_chapter: 1,
		source: 'ai',
		confidence: 0.92,
		book_ids: [1]
	},
	{
		id: 4,
		name: 'Baron Vladimir Harkonnen',
		also_known_as: [],
		role: 'antagonist',
		short_bio: 'The scheming ruler of House Harkonnen.',
		long_bio: null,
		tags: ['baron', 'schemer'],
		archetype: 'power-hungry villain',
		first_appearance_chapter: 3,
		source: 'ai',
		confidence: 0.9,
		book_ids: [1]
	},
	{
		id: 5,
		name: 'Gurney Halleck',
		also_known_as: [],
		role: 'supporting',
		short_bio: 'The Atreides weapons master and a skilled musician.',
		long_bio: null,
		tags: ['warrior', 'troubadour'],
		archetype: 'loyal warrior',
		first_appearance_chapter: 2,
		source: 'ai',
		confidence: 0.88,
		book_ids: [1]
	},
	{
		id: 6,
		name: 'Duncan Idaho',
		also_known_as: [],
		role: 'supporting',
		short_bio: 'Swordmaster of the Atreides.',
		long_bio: null,
		tags: ['swordmaster'],
		archetype: 'heroic warrior',
		first_appearance_chapter: 2,
		source: 'ai',
		confidence: 0.87,
		book_ids: [1]
	},
	{
		id: 7,
		name: 'Thufir Hawat',
		also_known_as: [],
		role: 'minor',
		short_bio: 'Mentat and Master of Assassins.',
		long_bio: null,
		tags: ['mentat'],
		archetype: 'loyal advisor',
		first_appearance_chapter: 2,
		source: 'ai',
		confidence: 0.85,
		book_ids: [1]
	},
	{
		id: 8,
		name: 'Chani',
		also_known_as: [],
		role: 'supporting',
		short_bio: "A Fremen warrior and Paul's love interest.",
		long_bio: null,
		tags: ['Fremen', 'warrior'],
		archetype: 'fierce love interest',
		first_appearance_chapter: 12,
		source: 'ai',
		confidence: 0.8,
		book_ids: [1]
	}
];
