# Generated by Django 6.0.5 on 2026-10-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('type', models.CharField(choices=[('book', 'Book'), ('character', 'Character'), ('place', 'Place'), ('universe', 'Universe')], max_length=16)),
                ('title', models.TextField()),
                ('book', models.TextField(blank=True, null=True)),
                ('universe', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('kind', models.CharField(choices=[('created', 'Created'), ('generation', 'Generation'), ('proposal', 'Proposal'), ('edit', 'Edit')], max_length=16)),
                ('author', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.page')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('owner', 'path'), name='unique_page_path_per_owner'),
        ),
    ]
