spring.application.name=springshelf
spring.datasource.url=jdbc:postgresql://localhost:5432/booksdb
spring.datasource.username=postgres
spring.datasource.password=secret-key
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.oauth2.client.registration.github.client-id=Ov23likVoi7dTFvExrGY
spring.security.oauth2.client.registration.github.client-secret=da3310769f2458ba7aba372d56380ddc34bdea9a
spring.security.oauth2.client.registration.github.scope=stokuj:stokujmen@gmail.com

jwt.secret=^IjC^UAz!JWf*v2Tf%e4zLs4mc6B*SY345W5zigjcFp*Ma6C