services:
  django:
    image: ghcr.io/stokuj/storyshelf-django:main
    container_name: storyshelf-django
    expose:
      - "8000"
    env_file:
      - ../.env
    environment:
      DJANGO_ENV: prod
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secret-key}@db:5432/${POSTGRES_DB:-booksdb}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media:/app/media
    command: gunicorn config.wsgi -b 0.0.0.0:8000 -w 4
    healthcheck:
      test:
        - "CMD-SHELL"
        - "python -c \"import socket;s=socket.socket();s.settimeout(3);s.connect(('localhost',8000))\""
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  svelte:
    image: ghcr.io/stokuj/storyshelf-svelte:main
    container_name: svelte
    expose:
      - "3000"
    environment:
      PUBLIC_API_URL: https://${DOMAIN}/api
      INTERNAL_API_URL: http://django:8000/api
    restart: unless-stopped
    depends_on:
      - django
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  caddy:
    image: caddy:2-alpine
    container_name: storyshelf-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    depends_on:
      - svelte
      - django

  db:
    image: postgres:16
    container_name: books-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-booksdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret-key}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-booksdb}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  db-data:
  caddy-data:
  caddy-config:
  media:
