# Generated by Django 6.0.5 on 2026-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('library', '0004_alter_serie_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bookgenre',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='booktag',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author'), name='unique_book_author'),
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='unique_book_genre'),
        ),
        migrations.AddConstraint(
            model_name='booktag',
            constraint=models.UniqueConstraint(fields=('book', 'tag'), name='unique_book_tag'),
        ),
    ]
