# Generated by Django 6.0.5 on 2026-05-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='characterrelation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='characterrelation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='characterrelation',
            name='target',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='ner_result',
            new_name='ner_pending',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='content',
            new_name='text',
        ),
        migrations.DeleteModel(
            name='BookCharacter',
        ),
        migrations.DeleteModel(
            name='CharacterRelation',
        ),
        migrations.DeleteModel(
            name='StoryCharacter',
        ),
    ]
