# Generated by Django 6.0.5 on 2026-05-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_ai_extraction_status'),
        ('library', '0004_alter_serie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='role',
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genre_through', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genre_through', to='library.genre'),
        ),
    ]
