# Generated by Django 6.0.5 on 2026-05-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_bookauthor_role_alter_bookgenre_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
