# Generated by Django 6.0.5 on 2026-05-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ai_extraction_failure_reason',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ai_extraction_finished_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ai_extraction_started_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ai_extraction_status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='text',
        ),
    ]
